
.TH BOTUSR 1

.SH NAME
botusr \- Bot user operations

.SH SYNOPSIS

.B botusr
[COMMAND] [OPTIONS]

.SH COMMANDS AVAILABLE

.B list
\- list the users of a bot

.RS
$ botusr list BOT_NAME
.RE

.B invite
\- invite a bot user by e-mail

.RS
$ botusr invite BOT_NAME USER_EMAIL
.RE

.B uninvite
\- remove a bot user

.RS
$ botusr invite BOT_NAME USER_EMAIL
.RE

.SH SEE ALSO
mkadmin(1) rmadmin(1)

.SH AUTHOR
Diego Guzman (diego.guzman@wizeline.com)
