.TH READBOT 1

.SH NAME
readbot \- Read properties of a bot

.SH SYNOPSIS

.B readbot
BOT_NAME[.PROPERTY]

Properties supported: id, name, integrations, nlp, qna, users, admins, customers

.RS
$ readbot BOT_NAME
.RE

.RS
$ readbot BOT_NAME.id
.RE

.RS
$ readbot BOT_NAME.integrations
.RE

.RS
$ readbot BOT_NAME.nlp
.RE

.RS
$ readbot BOT_NAME.qna
.RE

.RS
$ readbot BOT_NAME.users
.RE

.RS
$ readbot BOT_NAME.customers
.RE

.RS
$ readbot BOT_NAME.admins
.RE

.SH AUTHOR
Diego Guzman (diego.guzman@wizeline.com)
